update rules for jj
Output for trying to modify an immutable commit has changed.

New output looks like:

```sh
$ jj rebase -r <ID OF AN IMMUTABLE CHANGE> --onto 'trunk()'
Error: Commit <SHA> is immutable
Hint: Could not modify commit: <ID OF AN IMMUTABLE CHANGE> <SHA> <COMMIT MESSAGE>
Hint: Immutable commits are used to protect shared history.
Hint: For more information, see:
      - https://docs.jj-vcs.dev/latest/config/#set-of-immutable-commits
      - `jj help -k config`, "Set of immutable commits"
Hint: This operation would rewrite <NUMBER> or more immutable commits.
```

---

`--allow-new` is deprecated in favor of `jj bookmark track`.
This is covered by the "hint: run"/"and try again" pattern/rule.

For example:

```sh
$ jj git push                         
Warning: Refusing to create new remote bookmark <BOOKMARK>@origin
Hint: Run `jj bookmark track <BOOKMARK> --remote=origin` and try again.
Nothing changed.
```

The case sensitivity of the suggestions (`err::<STUFF>`) was changed
(https://github.com/iffse/pay-respects/commit/5b7169028b4ea8bda63532fd8b4263ce2acce962 and
https://github.com/iffse/pay-respects/commit/80f4496a8045b6e4a7a3e7c14824714d2a1f4463#diff-54ea723241231828f6cea5e58275577fb2860c25d321b75dac6e01c75e5c831bL93-L95).
It was previously case-insensitive (undocumented), but is now case-sensitive. As a result, the suggestion broke.