fix unwrap panic on unexpected nix-index output
New output:
```
$ asdf
fish: Command not found: asdf

Unexpected output from nix-index:
  error: reading from the database at '/home/jakob/.cache/nix-index/files' failed.
  This may be caused by a corrupt or missing database, try (re)running `nix-index` to generate the database. 
  If the error persists please file a bug report at https://github.com/nix-community/nix-index.
  caused by: No such file or directory (os error 2)
  
pay-respects: No matching package found
```